"""empty message

Revision ID: a7c70458c15d
Revises: 62bd17a9b7c8
Create Date: 2020-06-19 21:59:02.030104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c70458c15d'
down_revision = '62bd17a9b7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mail', sa.VARCHAR(length=128), nullable=False),
    sa.Column('passwrod', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('img', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('discription', sa.TEXT(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('img', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
